<?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    echo 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    exit(1);
}

 require_once(\ProcessWire\wire('files')->compile('vendor_sendinblue' . '/composer/autoload_real.php',array('includes'=>true,'namespace'=>true,'modules'=>true,'skipIfNamespace'=>true)));

return ComposerAutoloaderInit14532637486ebe0cc8ef696f8fae4373::getLoader();
